### ISSUE TITLE
Store person information by organization to handle conflicting data reported by organizations 

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-IDS#17]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Nathan Clinton

**Authoring Organization(s)**
Center for Education Performance and Information (CEPI) in Michigan

**Email Address**
nathan.clinton@aemcorp.com

**Target Data Needed** 
We're coding this at CEPI and will submit the change to the community once the project is complete. 

**Use Case Title**
Education organizations provide conflicting data about students.

**Use Case Overview**
Students that attend multiple schools, particularly those at the same time, may have data incorrectly entered into student information systems or provide districts with incorrect or differing data.  This includes sex, birthdate, name, race/ethnicity, etc.  State Education Agencies must be able to collect and store this conflicting information in the IDS and data warehouse.  Conflicting data is often handled at the reporting level, or it may be reviewed and corrected during data quality validations.  Regardless, in the education world there are multiple systems of record (district, postsecondary institution, etc.) for student data and each needs to be trusted. 

**Pull Request Number(s) (If applicable)**

**Use Case Background**
Students attending multiple schools were found to have different birthdates in Michigan.  This is traditionally handled at the report level, so the CEDS data models need to be able to handle this scenario. 

**Components Affected**
*CEDS Integrated Data Store (complete IDS Design Overview Table)*

*CEDS Data Warehouse (complete DW Design Overview Table)*

*CEDS Data Migrations (complete Data Migration Impact Analysis Table)*

---

**INTEGRATED DATA STORE DESIGN OVERVIEW**

**Description of Proposed Changes**
Add OrganizationId to dbo.Person.  Note that this will create an additional step to determine uniqueness for a person.  Currently, uniqueness is down to the person level, but with this change, it is at the person and organization level.  To find a unique person record in the new format, you will need to filter by PersonIdentifier.Identifier and Person.OrganizationId.  We will leave Person.OrganizationId nullable for those that do not need to account for this scenario, meaning they can still refer to PersonIdentifier.Identifier to establish uniqueness. 

**As-Is Diagram**
![image](https://user-images.githubusercontent.com/27246381/76976198-e1ebfb00-68f0-11ea-95b9-e57dc5943a80.png)

**Proposed To-Be Diagram**
![image](https://user-images.githubusercontent.com/27246381/76976353-1364c680-68f1-11ea-8343-c9c418817ec7.png)

---

**DATA WAREHOUSE DESIGN OVERVIEW (Includes Dim, Fact, and Report tables)**

**Description of Proposed Changes**
Birthdate, Sex, CohortYear, and HispanicLatinoEthnicity will be moved out of DimK12Student, DimPsStudent, and any other person-related slowly changing dimensions and added directly to Fact tables.  This will require a new dimension table, DimSexes.  Still considering where to store HispanicLatinoEthnicity.  We may change DimRaces to DimRacesEthnicities, converting it to a junk table.  

---

**DATA MIGRATION IMPACT ANALYSIS**

**Description of Proposed Changes**
All scripts that handle person data will need to accommodate the addition of OrganizationId to dbo.Person, taking care to note that this field is nullable.

**Comment by ajackl** [comment]
I am opposed to this change.  The use case is very real but some things  need to be handled at the  data model level and some at the data process level.  Master Data Management  happens at the business process and  rules level not at the data model.   

This same solution can be executed by having multiple schemas or data structures to handle your data quality or  data collection process.  Every organization will handle  master data management in a different way so this adds  a level of complexity to the most fundamental objects and ASSUMES every person will always be associated  to an Org(generally true in education but not necessarily- particularly with the growing interest in Self-Sovereign Identity.

This is an important use case but should NOT be solved her and in this way.

**Comment by 4pins** [comment]
I have to agree with Alex, the path to Data Quality is not to mix the good with the bad.  Figuring out what is correct should be done before it hits these systems.  The current model reflects the vast number of use cases.  Additionally the proposed model complicates these use cases.  As such my position is that such a change should not be adopted by CEDS.

**Comment by tqwhite** [comment]
Dear CEDS,
 
This is the worst idea I have heard about since I became involved in data modeling. The proposal suggests that we replace the concept of a person with a bureaucratic frankenstein built from a collection of historical errors and guilt by association. Worse, the proposal wants us to continue to use the world ‘person’ to reference this unholy mix.
 
Perhaps I am idiosyncratic but I understand the idea of data modeling to be finding a way to represent real things in digital for in a way that serves a purpose.  We have a roster. This is a digital representation of a class list so we can know who is supposed to be in a room. We have a school. This is a representation of, well, a school so we can send them nasty letters in the mail. If we manage to convince the federal government from redefining it, a person refers to a featherless biped that can get a drivers license.
 
You know the philisophical/physics idea of a person as a sort of worm-like sequence of snapshots through time. For each snap a person is in a particular position/ situation and then another and another. From this perspective, a person is the concatenation of all of his or her moments in time. It’s a technically valid way to think about a person because it is based on the physical truth of time.
 
We do not ever actually take this viewpoin. A person, in our reality, only exists at one time, now. Sure, that other view has its virtues but we don’t like it because it is useless. For example, we cannot accurately identify or know the details of all the moments or have any good way of specifying which one we are talking about. Instead, we say that a person exists and, when asked how tall they are, we measure the person and determine a value. This, knowing full well that the person was shorter before and will be again. Also, we aren’t making a coat for person’s throughout the timeline. We are making it today. We don’t ’trust’ the previous information because it is not true now.
 
This proposal similarly considers a person to be a concatenation of many things but in this case, the thing is a representation of the association between an organization of some sort and a collection of data that, one supposes, accommodates a variety of assertions about the person, all of which are either untrue or redundant.
 
The proposal doesn’t say why or when we should capture this pair, just that we would and that, to know who a person is, we would ask for them by two IDs, a person ID and an organization ID. How we would know which to choose is an exercise best left to the imagination… or nightmares.
 
This abomination is justified by asserting that some student has different birthdates at different schools. This attempts to ‘model’ a supposedly urgent real-world thing that never, in fact, has existed. There is not a single person, now or ever, who has two or more birthdates. There has never been a mother who delivered the same person twice. If this scenario has to be accommodated by the data model, then we may as well add data fields to characterize the nature of a person when he or she is a ghost and varying weight fields to accommodate situations where a person wants to be skinny.
 
But what’s even better is that the proposal says that these variations “ need to be trusted". If one school says the person is a boy and another says girl, who are we to judge? We add it to the data model and ’trust’ it. Sure, you might order the wrong kind of bathing suit but, at least you had a data object to justify the embarrassment of a student wearing, or not wearing, a bathing suit top that is inappropriate to the physical situation.
 
Even the phrase ‘use case’ is redefined in this proposal from the usual one of being a situation where a user wants to accomplish something to a statement of oddball conditions. No information is included that would allow us to imagine what the user is trying to accomplish in the case where two organization say different things about a person. Or why we would want to see a list of (mostly) erroneous birthdates. Or how we would choose which of the ’trusted’ variations we would use in some situation that nobody imagined but is worth changing the data model to accommodate.
 
I am opposed to this change to the data model on the grounds that it is an insult to the idea of a data model.
 
Sincerely, 
TQ White II

**Comment by jcampbell-aem** [comment]
There is nothing like a lively and spirited debated with peers who are invested in and care about education data. The feedback on this use case is appreciated and valued. The CEDS Open Source Community was developed for this very reason—to dialogue with peers!
 
As with all proposed changes, this use case will follow through the process defined for all submitted use cases including a thorough review of design options as well as a community assessment in which the proposed changes are vetted and assessed by CEDS stakeholders through a series of workgroup and review meetings.
 
While the use case makes its way through the documented process, I did want to take a moment to encourage continued open dialogue in an environment where comments are focused on the technical aspects of each use case submitted, potential implications to real world implementation and alternative solutions potentially identified.

**Comment by johnmannpaul** [comment]
From an SEA perspective I'm sympathetic to this use case and the proposed solution reminds me quite a lot of our own SIF based ODS in when each StudentPersonal and StaffPersonal is stamped with an originating system id that can ultimately be traced back to an organization. It allows the SEA to passively collect everyone's description of an individual without setting the bar so high that data won't make it into the system until everyone agrees on the same description. Our Id system also has its own master record that describes the individual (DOB, Gender, Name) and which is used to compare incoming Id requests against and score matches. Even the traits in this record, however, are modified according to who owns the enrollment and therefore is deemed to have a higher claim to the the truth. 

While I'm sympathetic, I also recognize the concern that the proposal raises. The proposed model seems to be replacing a set of canonical descriptions of individuals with a superset of descriptions of individuals by organization. While the original set of canonical individuals is isomorphic to the new set under the equivalence relation 'x has the same PersonIdentifier as y' it is not isomorphic to the new set itself as soon as there is more than one description for the same individual. So, the new model seems to subtly change the meaning of Person. 

By way of analogy it's kind of like if you replaced a table of 'RationalNumbers' that you were modeling with canonical pairs of integers with a table allowing any any conceivable pairs of integers and still insisted on calling the table 'RationalNumbers'. Even though what you had originally may be recoverable outside of the model, some information appears to have been lost.

**Comment by aemtriciafarris** [comment]
Join the OSC for a discussion around this proposed modification on 4/23 from 11am-12pm ET.

[https://meetings.ringcentral.com/j/1481779944](https://meetings.ringcentral.com/j/1481779944)

Telephone: 
    Dial(for higher quality, dial a number based on your current location): 
    US: +1(470)8692200 (US East) 
           +1(623)4049000 (US West) 
           +1(720)9027700 (US Central) 
           +1(773)2319226 (US North) 
           +1(469)4450100 (US South) 
    Meeting ID: 148 177 9944 
    International numbers available: https://meetings.ringcentral.com/teleconference

**Comment by tqwhite** [comment]
I sympathize with the problems caused by the fact that every person has records stored on computers all over the place. I have always struggled trying to imagine how to think about the highly variegated data sources that feed into our systems. In our case, we simply accept the last thing a district says as fact but we spend a fair amount of effort mitigating the consequences of their junk data as it poisons our databases.
 
**I would break the problem into two parts.** 

One is the thing we already do, decide what data about a person is correct. For this conversation, I refer to this as the 'canonical data' about a person. 
 
The other is what to do about the information received that is redundant or wrong. I take it that this proposal is an effort to deal with this second problem. The proposal’s text suggests that the problem that needs solving rests on the need for a data structure that will allow this non-canonical information to be stored and, where it can be helpful, trusted.
 
The solution to the problem should, in my opinion, derive from the uses to which the data can be applied. 
 
**An Example:**
 
If you were to look at the data representing me in various organizations, you would see two distinct versions of my name. In my high school database (as if they had such a thing in prehistoric times), I am Thomas Quayle White II. The same with University of California Berkeley, which did have a computer database. In my Social Security database record, I am TQ White II (no middle name) and I live in Mound, MN. The latter is correct today. It is the version that should be trusted.

Suppose though, a person who knew me in high school was trying to search for me. That person would look for Thomas who lives in Mound, MN. The current SIF data model would say that Thomas does not exist.
 
The proposal being made would support this problem by having the person ask the system to find a Thomas from Mound whose record comes from New Trier High School. Since that school didn’t actually have computers back then, the proposed data model would still say I did not exist. If the person thought to ask for a Thomas whose data came from Berkeley, I would be found. If they just asked for Thomas from Mound, no org, I would not be found.
 
The proposed change to the data model would support the use case where someone is trying to find a person knowing the 1) source of the records and 2) something about the identity  of the person they seek. I do not believe this is a use case that exists. Worse, without the addition of a ’trusted’ flag someplace, there is no way to know anything about the person today.
 
A better solution would support the use case where someone searches for Thomas White from Mound and then finds information about me, even though my canonical name is TQ. I think that this use case calls for the ability to accumulate information that is known to be about me in a way that is searchable. 
 
Another use case is to be able to present search terms based on past data loads, even those that are known to be problematic. Eg, a search for Thomas who went to New Trier that produces TQ from Mound.
 
I suppose a third, possible but unlikely, use case could be to audit the validity of data from previous data loads to find out what sources are more likely to produce trustworthy data.
 
All of these are separate from the use case of someone wanting to know the correct, canonical information about a person.
 
The final use case is supporting a person who needs a place to put new, possibly, incorrect, information when it arrives. Presumably this data would later be evaluated for inclusion in the canonical data record if it is found to be more correct or adds missing information. It may be kept anyway to support the other use cases.
 
**My Suggestion:**
 
Change to the data model to add yet another element to the student_personal (and, perhaps, other data elements with a similar need) perhaps called historical_personal_data_list_refId.
 
This would reference a new object that is a list that accumulates (ie, with an unbounded count), more or less, complete student_personal objects that are not considered correct. If it’s important, and I am not sure it is, that new history element could include an indication of the source. The source indication could either be the refId of one of the organization objects or a simple text descriptor. There might be other things that come from the outside that would be useful even if they have no analog in student_personal.

This begs, potentially, another use case where a user wants to find a person who has been previously associated with an organization, eg, who among us attended New Trier.

**Or, to say it more formally:**

**Use cases:**

1) Identify a user based on identity characteristics that are inaccurate or historical, including, perhaps, association with an historical data source or organization.

2) Store information that is not canonical for future evaluation and possible promotion to canonical status as it is receive.

3) Identify a user based on previous organizational associations.

**Data model change strategy:**

To the student_personal object, add a reference to a new historical_personal_data_list object that would accumulate an unlimited number of historical_personal_data objects.  Define the historical_personal_data element contained in this list to be an appropriate subset of the student_personal object with the addition of some sort of reference to the source of the data in this object and, perhaps, other things that are found to be useful.
 
Do not try to redefine the meaning of the student_personal object. Simply add an element to reference the object containing the stuff that motivates this proposal. Leave every other thing as it is so that nobody who does not need to support these use cases can ignore the change.

**Comment by tqwhite** [comment]
I sympathize with the problems caused by the fact that every person has records stored on computers all over the place. I have always struggled trying to imagine how to think about the highly variegated data sources that feed into our systems. In our case, we simply accept the last thing a district says as fact but we spend a fair amount of effort mitigating the consequences of their junk data as it poisons our databases.
 
**I would break the problem into two parts.** 

One is the thing we already do, decide what data about a person is correct. For this conversation, I refer to this as the 'canonical data' about a person. 
 
The other is what to do about the information received that is redundant or wrong. I take it that this proposal is an effort to deal with this second problem. The proposal’s text suggests that the problem that needs solving rests on the need for a data structure that will allow this non-canonical information to be stored and, where it can be helpful, trusted.
 
The solution to the problem should, in my opinion, derive from the uses to which the data can be applied. 
 
**An Example:**
 
If you were to look at the data representing me in various organizations, you would see two distinct versions of my name. In my high school database (as if they had such a thing in prehistoric times), I am Thomas Quayle White II. The same with University of California Berkeley, which did have a computer database. In my Social Security database record, I am TQ White II (no middle name) and I live in Mound, MN. The latter is correct today. It is the version that should be trusted.

Suppose though, a person who knew me in high school was trying to search for me. That person would look for Thomas who lives in Mound, MN. The current SIF data model would say that Thomas does not exist.
 
The current suggestion would support this problem by having the person ask the system to find a Thomas from Mound whose record comes from New Trier High School. Since that school didn’t actually have computers back then, the proposed data model would still say I did not exist. If the person thought to ask for a Thomas whose data came from Berkeley, I would be found. If they just asked for Thomas from Mound, no org, I would not be found.

 
__Use Cases__

The proposed change to the data model would support the use case where someone is trying to find a person knowing the 1) source of the records and 2) something about the identity  of the person they seek. I do not believe this is a use case that exists. Worse, without the addition of a ’trusted’ flag someplace, there is no way to know anything about the person today.
 
A better solution would support the use case where someone searches for Thomas White from Mound and then finds information about me, even though my canonical name is TQ. I think that this use case calls for the ability to accumulate information that is known to be about me in a way that is searchable. 
 
Another use case is to be able to present search terms based on past data loads, even those that are known to be problematic. Eg, a search for Thomas who went to New Trier that produces TQ from Mound.
 
I suppose a third, possible but unlikely, use case could be to audit the validity of data from previous data loads to find out what sources are more likely to produce trustworthy data.
 
All of these are separate from the use case of someone wanting to know the correct, canonical information about a person.
 
The final use case is supporting a person who needs a place to put new, possibly, incorrect, information when it arrives. Presumably this data would later be evaluated for inclusion in the canonical data record if it is found to be more correct or adds missing information. It may be kept anyway to support the other use cases.
 
**My Suggestion:**
 
Change to the data model to add yet another element to the student_personal (and, perhaps, other data elements with a similar need) perhaps called historical_personal_data_list_refId.
 
This would reference a new object that is a list that accumulates (ie, with an unbounded count), more or less, complete student_personal objects that are not considered correct. If it’s important, and I am not sure it is, that new history element could include an indication of the source. The source indication could either be the refId of one of the organization objects or a simple text descriptor. There might be other things that come from the outside that would be useful even if they have no analog in student_personal.

This begs, potentially, another use case where a user wants to find a person who has been previously associated with an organization, eg, who among us attended New Trier.

**Or, to say it more formally:**

**Use cases:**

1) Identify a user based on identity characteristics that are inaccurate or historical, including, perhaps, association with an historical data source or organization.

2) Store information that is not canonical for future evaluation and possible promotion to canonical status as it is receive.

3) Identify a user based on previous organizational associations.

**Data model change strategy:**

To the student_personal object, add a reference to a new historical_personal_data_list object that would accumulate an unlimited number of historical_personal_data objects.  Define the historical_personal_data element contained in this list to be an appropriate subset of the student_personal object with the addition of some sort of reference to the source of the data in this object and, perhaps, other things that are found to be useful.
 
Do not try to redefine the meaning of the student_personal object. Simply add an element to reference the object containing the stuff that motivates this proposal. Leave every other thing as it is so that nobody who does not need to support these use cases can ignore the change.

**Comment by martinbherbener** [comment]
Hi,

FYI, at least one major SIS takes an approach similar to what @tqwhite suggests - it clearly identifies a name/birthdate/etc. that are considered current/canonical/most correct, while tracking prior/other "versions" of those values.

thanks

Martin

**Comment by aemtriciafarris** [comment]
Join the OSC for a continued discussion / work group on this topic on 6/3 from 12-1 ET.

PC, Mac, Linux, iOS or Android: https://meetings.ringcentral.com/j/1484437391 
Or iPhone one-tap : 
    US: +1(773)2319226,,1484437391# (US North) 
           +1(469)4450100,,1484437391# (US South) 
           +1(470)8692200,,1484437391# (US East) 
           +1(623)4049000,,1484437391# (US West) 
           +1(720)9027700,,1484437391# (US Central) 
Or Telephone: 
    Dial(for higher quality, dial a number based on your current location): 
    US: +1(773)2319226 (US North) 
           +1(469)4450100 (US South) 
           +1(470)8692200 (US East) 
           +1(623)4049000 (US West) 
           +1(720)9027700 (US Central) 
    Meeting ID: 148 443 7391 
    
Also, the recording for the first meeting on 4/23 can be found here: 
https://www.youtube.com/watch?v=Qx5Au5KlZk0

**Comment by aemnathanclinton** [comment]
A solution was found that didn't require changes to the IDS data model.

**Comment by johnmannpaul** [comment]
What was the solution?
